prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select * 
where 
{ 
  ?s a ?o .
  filter(isiri(?s))
  filter(strstarts(xsd:string(?s), "http://purl.obolibrary.org/obo/ENVO_"))
  bind(xsd:integer(strafter(xsd:string(?s), "http://purl.obolibrary.org/obo/ENVO_")) as ?suffix)
  # bind(xsd:string(?s) as ?sstr)
} limit 9

# http://purl.obolibrary.org/obo/ENVO_03600000
