prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select distinct ?suffix
where 
{ 
  ?s a ?o .
  filter(isiri(?s))
  filter(strstarts(xsd:string(?s), "http://purl.obolibrary.org/obo/ENVO_"))
  bind(xsd:integer(strafter(xsd:string(?s), "http://purl.obolibrary.org/obo/ENVO_")) as ?suffix)
}
order by ?suffix
